application: o--v--o
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /libs
  static_dir: libs

- url: /.*
  script: doubi.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- channel_presence